### PR TITLE
Added tutorial for web scraping using covid data

### PR DESCRIPTION
**Pull request by ManthanShettigar**
Project Outline

    1. to scrape the covid statistics from https://epidemic-stats.com/
    2. get a list of infected,deaths,recovered stats country wise
    3 .create a CSV file in the following format:

> country,infected,deaths,recovered,death_percent,recovered_percent 
USA,35688506,629064,29652038,1.8,83.1
India,31613993,423842,30781263,1.3,97.4

### CODE REVIEW

**Comment by divyanshugarg36** [comment]
Looks like you have sent the wrong file. Please send code files to scrap data.

**Comment by ManthanShettigar** [comment]
@divyanshugarg36  Its the right file sir , please open up the file in jupyter notebook (language used is python) . I have also added explanation of code (this is why I have used jupyter notebook instead of python file)

**Comment by ManthanShettigar** [comment]
If you want i will convert it into .py .but the images and explanations will be removed from the .py file because it cannot display images(important aspect of a tutorial)

**Comment by divyanshugarg36** [comment]
Okay sure i will check this one and merge once confirmed.

**Comment by ManthanShettigar** [comment]
Sure , do let me know if anything else needed!

**Pull request merged**
